library_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    ValidationError,
)
import re
from library_app.models import User
from wtforms.validators import DataRequired

class ResetRequestForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired()])
    submit = SubmitField("Request Reset")

    def validate_email(self, email):
        pattern = r"^([a-z\d\.-]+)@([a-z\d-]+)\.([a-z]{2,8})(\.[a-z]{2,8})?$"
        if not re.match(pattern, email.data):
            raise ValidationError("Invalid email address.")
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError(
                "There is no account with that email. You must register first."
            )

library_app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user
from library_app import db, bcrypt
from library_app.models import User, Section, Book
from library_app.utils import check_user
from library_app.forms import ResetPasswordForm
from library_app.main.forms import ResetRequestForm
from library_app.utils import send_reset_email

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
@main.route("/sections")
@check_user()
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    return render_template(
        "main/sections.html",
        title="Sections",
        navbaractive=["Sections"],
        sections=sections,
    )


@main.route("/main/search", methods=["GET", "POST"])
@check_user()
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        return render_template(
            "main/search.html",
            title="Search",
            user=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("main.books"))


@main.route("/section-books/<int:sectionid>")
@check_user()
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (sum(feedback.rating for feedback in x.feedbacks), x.date_created),
        reverse=True,
    )
    return render_template(
        "main/section_books.html",
        title=f"{section.title} Books",
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@main.route("/books")
@check_user()
def books():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sorted_sections = []
    for section in sections:
        sorted_books = sorted(
            section.books,
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        sorted_sections.append((section, sorted_books))
    return render_template(
        "main/books.html",
        title="Books",
        navbaractive=["Books"],
        sorted_sections=sorted_sections,
    )


@main.route("/book-info/<int:bookid>")
@check_user()
def book_info(bookid):
    book = Book.query.get(bookid)
    if book is None:
        flash("Book not found", "danger")
        return redirect(url_for("user.books"))
    feedbacks = sorted(
        book.feedbacks, key=lambda x: (x.rating, x.date_created), reverse=True
    )
    pdf_file = url_for("static", filename="book/pdfs/" + book.pdf_file)
    return render_template(
        "main/book_info.html",
        title="Books",
        book=book,
        feedbacks=feedbacks,
        pdf_file=pdf_file,
        navbaractive=["Books"],
        sections=sections,
    )


@main.route("/reset-request", methods=["GET", "POST"])
@check_user()
def reset_request():
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user, 'main.reset_password')
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_request.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )


@main.route("/reset-password/<token>", methods=["GET", "POST"])
@check_user()
def reset_password(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token.", "warning")
        return redirect(url_for("main.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.new_password.data).decode(
            "utf-8"
        )
        db.session.commit()
        flash("Your password has been updated!", "success")
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_password.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )

library_app/user/routes.py
import secrets
from datetime import datetime, timezone
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    request,
)
from flask_login import login_user, current_user, logout_user
from library_app import db, bcrypt
from library_app.models import User, Section, Request, Feedback, IssuedBook, Book
from library_app.forms import (
    LoginForm,
    EditProfileForm,
    ChangePasswordForm,
    ResetPasswordForm,
    DeleteAccountForm,
)
from library_app.user.forms import (
    RegistrationForm,
    BookRequestForm,
    FeedbackForm,
    EditFeedbackForm,
)
from library_app.utils import (
    login_required,
    check_user,
    save_picture,
    send_reset_email,
    delete_file,
)
from library_app.user.utils import generate_plots

user = Blueprint("user", __name__)


@user.route("/user/register", methods=["GET", "POST"])
@check_user()
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if form.profile_picture.data:
            profile_picture = save_picture(form.profile_picture.data, "user\\profile_pictures")
        else:
            profile_picture = "default_profile_picture.png"
        user = User(
            name=form.name.data,
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
            profile_picture=profile_picture,
        )
        print(form.profile_picture.data, user)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}!", "success")
        return redirect(url_for("user.login"))
    return render_template(
        "user/register.html",
        user=current_user,
        title="Register",
        form=form,
        navbaractive=["Login"],
    )


@user.route("/user/login", methods=["GET", "POST"])
@check_user()
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.urole == "user":
                flash(f"You have logged in successfully!", "success")
                login_user(user, remember=form.remember.data)
                nextpage = request.args.get("next")
                return (
                    redirect(nextpage) if nextpage else redirect(url_for("user.books"))
                )
            elif user.urole == "librarian":
                flash(f"Please log in as librarian", "info")
                return redirect(url_for("librarian.login"))
            else:
                return redirect(url_for("main.error"))
        else:
            flash(f"Invalid username or Password", "danger")
    return render_template(
        "user/login.html", title="Login", form=form, navbaractive=["Login"], width=True
    )


@user.route("/user/sections")
@login_required(role="user")
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    return render_template(
        "user/sections.html",
        title="Sections",
        navbaractive=["Sections"],
        user=current_user,
        sections=sections,
    )


@user.route("/user/search", methods=["GET", "POST"])
@login_required(role="user")
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        books.sort(
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        authors.sort(
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        return render_template(
            "user/search.html",
            title="Search",
            user=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("user.books"))


@user.route("/user/section-books/<int:sectionid>")
@login_required(role="user")
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (
            sum(feedback.rating for feedback in x.feedbacks),
            x.date_created,
        ),
        reverse=True,
    )
    return render_template(
        "user/section_books.html",
        title=f"{section.title} Books",
        user=current_user,
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@user.route("/user/books")
@login_required(role="user")
def books():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sorted_sections = []
    for section in sections:
        sorted_books = sorted(
            section.books,
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        sorted_sections.append((section, sorted_books))
    issuedbookids = {
        issuedbook.bookid: issuedbook.issueid
        for issuedbook in current_user.issuedbooks
        if issuedbook.status == "current"
    }
    feedbackbookids = {
        feedback.bookid: feedback.feedbackid
        for feedback in current_user.feedbacks
        if feedback.bookid in issuedbookids
    }
    return render_template(
        "user/books.html",
        title="Books",
        user=current_user,
        navbaractive=["Books"],
        issuedbookids=issuedbookids,
        feedbackbookids=feedbackbookids,
        sorted_sections=sorted_sections,
    )


@user.route("/user/book-info/<int:bookid>")
@login_required(role="user")
def book_info(bookid):
    book = Book.query.get(bookid)
    if book is None:
        flash("Book not found", "danger")
        return redirect(url_for("user.books"))
    feedbacks = sorted(
        book.feedbacks, key=lambda x: (x.rating, x.date_created), reverse=True
    )
    pdf_file = url_for("static", filename="book/pdfs/" + book.pdf_file)
    issuedbookids = {
        issuedbook.bookid: issuedbook.issueid
        for issuedbook in current_user.issuedbooks
        if issuedbook.status == "current"
    }
    feedbackbookids = {
        feedback.bookid: feedback.feedbackid
        for feedback in current_user.feedbacks
        if feedback.bookid in issuedbookids
    }
    return render_template(
        "user/book_info.html",
        title="Books",
        user=current_user,
        book=book,
        feedbacks=feedbacks,
        issuedbookids=issuedbookids,
        feedbackbookids=feedbackbookids,
        pdf_file=pdf_file,
        navbaractive=["Books"],
        sections=sections,
    )


@user.route("/user/book-request/<int:bookid>", methods=["GET", "POST"])
@login_required(role="user")
def book_request(bookid):
    cou1 = 0
    for issuedbook in current_user.issuedbooks:
        if issuedbook.bookid == bookid and issuedbook.status=="current":
            flash("The book has already been issued.", "info")
            return redirect(url_for("user.books"))
        if issuedbook.status == "current":
            cou1 += 1
    cou2 = 0
    for user_request in current_user.requests:
        if user_request.bookid == bookid and user_request.status == "pending":
            flash("The request has already been placed.", "info")
            return redirect(url_for("user.books"))
        if user_request.status == "pending":
            cou2 += 1
    if cou1 + cou2 >= 5:
        flash("You can only borrow 5 books at maximum.", "danger")
        return redirect(url_for("user.mybooks"))
    form = BookRequestForm()
    if form.validate_on_submit():
        book_request = Request(
            userid=current_user.userid,
            days=form.days.data,
            bookid=form.bookid.data,
        )
        db.session.add(book_request)
        db.session.commit()
        flash(f"The book has been requested!", "success")
        return redirect(url_for("user.mybooks"))
    if request.method == "GET":
        form.bookid.data = bookid
        form.days.data = 3
    return render_template(
        "user/book_request.html",
        title="Book Request",
        form=form,
        user=current_user,
        navbaractive=["Books"],
    )


@user.route("/user/delete-request/<int:requestid>")
@login_required(role="user")
def delete_request(requestid):
    book_request = Request.query.get(requestid)
    if book_request:
        if current_user.userid == book_request.userid:
            flash("The request has been deleted.", "success")
            db.session.delete(book_request)
            db.session.commit()
        else:
            abort(403)
    else:
        flash("The book doesn't exist", "danger")
    return redirect(url_for("user.mybooks"))


@user.route("/user/mybooks")
@login_required(role="user")
def mybooks():
    current, completed = [], []
    for issuedbook in IssuedBook.query.filter_by(userid=current_user.userid).all():
        if issuedbook.status == "current":
            if datetime.now(timezone.utc).date() > issuedbook.to_date:
                issuedbook.status = "returned"
                db.session.commit()
        if issuedbook.status == "current":
            current.append(issuedbook)
        else:
            completed.append(issuedbook)
    current.sort(
        key=lambda x: (
            x.to_date,

library_app/templates/main/book_info.html
{% extends "main/layout.html" %} {% block content %}
<div class="container content-section px-5 pt-4 pb-4">
    <div class="row">
        <div class="mr-4 mb-3">
            <img
                src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                alt="{{ book.title }}"
                class="img-fluid special-card"
                style="height: 25vh"
            />
        </div>
        <div class="">
            <h2>{{ book.title }}</h2>
            <h5>{{ book.author }}</h5>
            <h6>{{ book.section.title }}</h6>
            <p>{{ book.description }}</p>
            <div class="mt-1 mb-3">
                <a
                    href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                    class="btn btn-success"
                    ><i class="bi bi-send mr-1"></i>Request</a
                >
            </div>
        </div>
    </div>
    <hr />
    <h2 class="text-center">Preview</h2>
    <div class="mt-3" id="pdf-viewer" style="text-align: center;"></div>
    <hr />
    <div class="row mt-3">
    <div class="col-md-12">
        <h2 class="mb-3">Feedbacks</h2>
        {% if feedbacks %}
            <div class="list-group">
                {% for feedback in feedbacks %}
                    <div class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ feedback.user.name }}</h5>
                            <small>{{ feedback.date_created }}</small>
                        </div>
                        <div class="d-flex w-100 justify-content-between">
                            <p class="mb-1">Rating: {{ feedback.rating }}/5</p>
                        </div>
                        <p class="mb-1">{{ feedback.content }}</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No feedback available for this book.</p>
        {% endif %}
    </div>
</div>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.js"></script>
<script>
    const pdfPath = "{{ pdf_file }}";
    const viewerContainer = document.getElementById('pdf-viewer');
    const loadingTask = pdfjsLib.getDocument(pdfPath);
    loadingTask.promise.then(pdf => {
        for (let pageNum = 1; pageNum <= 1; pageNum++) {
            pdf.getPage(pageNum).then(page => {
                const container = document.createElement('div');
                container.className = 'pdf-page';
                container.style.display = 'inline-block';
                container.style.margin = '0 auto';
                container.style.marginBottom = '10px';
                container.style.border = '1px solid #ccc';
                viewerContainer.appendChild(container);

                const canvas = document.createElement('canvas');
                container.appendChild(canvas);

                const context = canvas.getContext('2d');
                const viewport = page.getViewport({ scale: 1 });
                const scale = 600 / viewport.height;
                const scaledViewport = page.getViewport({ scale });

                canvas.height = scaledViewport.height;
                canvas.width = scaledViewport.width;

                const renderContext = {
                    canvasContext: context,
                    viewport: scaledViewport
                };
                page.render(renderContext);
            });
        }
    });
</script>
{% endblock %}

library_app/templates/main/books.html
{% extends "main/layout.html" %} {% block content %}
<div class="content-section container px-4 pb-4">
{% for section, sorted_books in sorted_sections %} {% if sorted_books|length>4
%}
<div class="container mt-4">
    <a href="{{url_for("main.section_books", sectionid=section.sectionid)}}" style="text-decoration:none;"><h2 class="mr-5 mt-3">{{ section.title }}</h2></a>
    <div class="container-fluid mt-3">
        <div class="row flex-row flex-nowrap">
            {% for book in sorted_books %}
            <div class="container">
                <div class="card special-card mx-1" style="width: 16rem">
                    <a href="{{ url_for('main.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                    <img
                        class="card-img-top mx-auto"
                        src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                        alt="Card image cap"
                        style="width: 100%; height: 24vh"
                    />
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <h6 class="card-title">{{ book.author }}</h6>
                        <p class="card-text text-wrap">{{ book.description }}</p>
                    </div>
                    </a>
                    <div class="container mt-1 mb-3 text-center">
                        <a
                            href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                            class="btn btn-success"
                            ><i class="bi bi-send mr-1"></i>Request</a
                        >
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% elif sorted_books|length!=0 %}
<div class="container mt-4">
    <a href="{{url_for("main.section_books", sectionid=section.sectionid)}}" style="text-decoration:none;"><h2 class="mr-5 mt-3">{{ section.title }}</h2></a>
    <div class="row mt-3">
        {% for book in sorted_books %}
        <div class="col-md-3">
            <div class="card special-card mx-1">
                <a href="{{ url_for('main.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                <img
                    class="card-img-top mx-auto"
                    src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                    alt="Card image cap"
                    style="width: 100%; height: 24vh"
                />
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <h6 class="card-title">{{ book.author }}</h6>
                    <p class="card-text text-wrap">{{ book.description }}</p>
                </div></a>
                <div class="container mt-1 mb-3 text-center">
                    <a
                        href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                        class="btn btn-success"
                        ><i class="bi bi-send mr-1"></i>Request</a
                    >
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="container mt-4">
    <a href="{{url_for("main.section_books", sectionid=section.sectionid)}}" style="text-decoration:none;"><h2 class="mr-5 mt-3">{{ section.title }}</h2></a>
    <h4 class="mr-5 mt-2">There are no Books in this Section</h2>
</div>
{% endif %} {% endfor %}
</div>
{% endblock content %}

library_app/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='main/style.css') }}"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='main/favicon.ico') }}">
        {% if title %}
        <title>Main - {{ title }}</title>
        {% else %}
        <title>Main - eLibrary</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="mr-4" href="{{url_for("main.sections")}}"><img class="logo-img" src="{{url_for('static', filename="main/library_logo.jpg")}}"/></a>
                    <div class="container">
                        <form id="searchForm" class="form-inline mx-auto search-form" action="{{ url_for('main.search') }}" method="POST" style="width: 37vw; height: 5.4vh;">
                            <div class="input-group">
                                <input id="searchInput" name="search_term" class="form-control form-control-lg border-right-0" type="search" placeholder="Search..." aria-label="Search" style="height: 5.4vh;" minlength="1" maxlength="60">
                                <div class="input-group-append">
                                    <button class="btn btn-lg btn-outline-success border-left-0" type="submit" style="height: 5.4vh;">
                                        <i class="bi bi-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="navbar-nav">
                        <a class="nav-item nav-link h5 font-weight-normal mt-2 mx-2 {%if 'Sections' in navbaractive%} active {%endif%}" href="{{url_for("main.sections")}}">Sections</a>
                        <a class="nav-item nav-link h5 font-weight-normal mt-2 mx-2 {%if 'Books' in navbaractive%} active {%endif%}" href="{{url_for("main.books")}}">Books</a>
                        <a class="nav-item nav-link h5 font-weight-normal mt-2 mx-2 {%if 'Login' in navbaractive%} active {%endif%}" href="{{url_for("user.login")}}">Login</a>
                    </div>
                </div>
            </nav>
        </header>
        {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
                <div class="container mx-auto w-{% if width %}25{% else %}50{% endif %}" style="margin-top: 11vh">
                    {% for category, message in messages%}
                        <div class="alert alert-{{category}}">{{message}}</div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="container mx-auto w-50" style="margin-top: 14vh"> </div>
            {% endif %}
        {% endwith %}
        {% block content %} {% endblock %}
        <script src="{{url_for('static', filename='main/script.js')}}" ></script>
        <p class="mb-5"></p>
        <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

library_app/templates/main/reset_password.html
{% extends "main/layout.html" %} {% block content %}
<div class="content-section mx-auto w-50">
<form
    method="POST"
    action=""
    class="form w-75 mx-auto mt-3 mb-3"
    style="display: flexbox; justify-content: center; align-items: center"
>
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 h2 font-weight-normal">
            Reset Password
        </legend>
        <div class="form-group">
            {{ form.new_password.label(class='h5 font-weight-normal
            form-control-label mt-2') }} {% if form.new_password.errors %} {{
            form.new_password(class="form-control form-control-lg is-invalid
            mt-1") }}
            <div>
                {% for error in form.new_password.errors %}
                <p class="text-danger mt-1">*{{error}}</p>
                {% endfor %}
            </div>

            {% else %} {{ form.new_password(class="form-control form-control-lg
            mt-1") }} {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class='h5 font-weight-normal
            form-control-label mt-2') }} {% if not form.new_password.errors and
            form.confirm_password.errors %} {{
            form.confirm_password(class="form-control form-control-lg is-invalid
            mt-1") }}
            <div>
                {% for error in form.confirm_password.errors %}
                <p class="text-danger mt-1">*{{error}}</p>
                {% endfor %}
            </div>
            {% else %} {{ form.confirm_password(class="form-control
            form-control-lg mt-1") }} {% endif %}
        </div>
        <div>
            <input type="checkbox" id="showPass" onchange="showPassword()">
            <label for="showPass">Show</label>
        </div>
    </fieldset>
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-lg btn-danger" href="{{url_for("main.reset_request")}}"><i class="bi bi-x-circle mr-1"></i>Cancel</a>
        </div>
        <div class="col-md-6 text-right">
            <button class="btn btn-lg btn-success" id="submit" name="submit" type="submit" value="Reset Password"><i class="bi bi-lock"></i>Reset Password</button>
        </div>
    </div>
    <div class="container mt-3"></div>
    <a href="{{url_for('user.register')}}" style="font-size: 1.15rem;">Don't Have An Account?</a>
</form>
{% endblock content %}

library_app/templates/main/section_books.html
{% extends "main/layout.html" %} 
{% block content %}
<div class="container content-section px-5 pt-4 pb-4">
    <div class="row">
        <div class="mr-4 mb-3">
            <img src="{{ url_for('static', filename='section/' + section.picture) }}" alt="{{ section.title }}" class="img-fluid special-card" style="max-height: 200px;">
        </div>
        <div class="">
            <h1 class="mb-3">{{ section.title }}</h1>
            <p>{{ section.description }}</p>
        </div>
    </div>
    <hr />
    {% if sorted_books|length > 0 %}
    <h2 class="mb-2 mt-3">Books</h2>
    {% for book in sorted_books %}
        {% if loop.index0 % 4 == 0 %}
        <div class="row mt-3">
        {% endif %}
        <div class="col-md-3 mt-3">
            <div class="card h-100 special-card mx-1">
                <a href="{{ url_for('main.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                <img class="card-img-top mx-auto" src="{{ url_for('static', filename='book/pictures/' + book.picture) }}" alt="Card image cap" style="width: 100%; height: 25vh;">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <h6 class="card-title">{{ book.author }}</h6>
                    <p class="card-text text-wrap">{{ book.description }}</p>
                </div></a>
                <div class="container mt-1 mb-3 text-center">
                    <a href="{{ url_for('user.book_request', bookid=book.bookid) }}" class="btn btn-success"><i class="bi bi-send mr-1"></i>Request</a>
                </div>
            </div>
        </div>
        {% if loop.index % 4 == 0 or loop.last %}
        </div>
        {% endif %}
    {% endfor %}
    {% else %}
    <div class="mt-4">
        <h2 class="mb-3">Books</h2>
        <h4 class="mt-3">There are no Books in this Section</h4>
    </div>
    {% endif %}
</div>
{% endblock content %}