library_app/librarian/routes.py
import secrets
from datetime import date, datetime, timezone, timedelta
from flask import (
    request,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    Blueprint,
)
from sqlalchemy.exc import SQLAlchemyError
from flask_login import login_user, current_user, logout_user
from library_app import db, bcrypt
from library_app.models import User, Section, Book, Request, IssuedBook
from library_app.utils import (
    login_required,
    save_picture,
    send_reset_email,
    delete_file,
)
from library_app.librarian.utils import save_pdf, generate_plots
from library_app.forms import (
    LoginForm,
    EditProfileForm,
    ChangePasswordForm,
    ResetPasswordForm,
    DeleteAccountForm,
)
from library_app.librarian.forms import (
    AddSectionForm,
    EditSectionForm,
    AddBookForm,
    EditBookForm,
)


librarian = Blueprint("librarian", __name__)


@librarian.route("/librarian/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        librarian = User.query.filter_by(username=form.username.data).first()
        if librarian and bcrypt.check_password_hash(
            librarian.password, form.password.data
        ):
            if librarian.urole == "librarian":
                flash("You have logged in successfully!", "success")
                login_user(librarian, remember=form.remember.data)
                nextpage = request.args.get("next")
                return (
                    redirect(nextpage)
                    if nextpage
                    else redirect(url_for("librarian.sections"))
                )
            elif librarian.urole == "user":
                flash("Please log in as user.", "info")
                return redirect(url_for("user.login"))
            else:
                return redirect(url_for("main.error"))
        else:
            flash(f"Invalid Username or Password", "danger")
    return render_template(
        "librarian/login.html",
        title="Login",
        form=form,
        navbaractive=["Login"],
        width=True,
    )


@librarian.route("/librarian/add-section", methods=["GET", "POST"])
@login_required(role="librarian")
def add_section():
    form = AddSectionForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture = save_picture(form.picture.data, "section")
        else:
            picture = "default_section_picture.jpeg"
        section = Section(
            title=form.title.data,
            description=form.description.data,
            picture=picture,
        )
        db.session.add(section)
        db.session.commit()
        flash(f"New Section {form.title.data} created!", "success")
        return redirect(url_for("librarian.sections"))
    return render_template(
        "librarian/add_section.html",
        title="Add Section",
        form=form,
        librarian=current_user,
        navbaractive=["Sections"],
    )


@librarian.route("/librarian/edit-section/<int:sectionid>", methods=["GET", "POST"])
@login_required(role="librarian")
def edit_section(sectionid):
    if sectionid==1:
        abort(403) 
    section = Section.query.get(sectionid)
    form = EditSectionForm(current_section=section)
    if form.validate_on_submit():
        if (
            form.picture.data
            or form.delete_picture.data == "yes"
            or section.title != form.title.data
            or section.description != form.description.data
        ):
            flash("Section has been updated!", "success")
        if form.picture.data:
            if section.picture != "default_section_picture.jpeg":
                delete_file("section", section.picture)
            section.picture = save_picture(form.picture.data, "section")
        elif form.delete_picture.data == "yes":
            if section.picture != "default_section_picture.jpeg":
                delete_file("section", section.picture)
            section.picture = "default_section_picture.jpeg"
        section.date_created = datetime.now(timezone.utc).date()
        section.title = form.title.data
        section.description = form.description.data
        db.session.commit()
        return redirect(url_for("librarian.section_books", sectionid=sectionid))
    if request.method == "GET":
        form.title.data = section.title
        form.description.data = section.description
    return render_template(
        "librarian/edit_section.html",
        title="Edit Section",
        form=form,
        section=section,
        librarian=current_user,
        navbaractive=["Sections"],
    )


@librarian.route("/librarian/delete-section/<int:sectionid>")
@login_required(role="librarian")
def delete_section(sectionid):
    if sectionid==1:
        abort(403)
    section = Section.query.get(sectionid)
    if section:
        try:
            if section.picture != "default_section_picture.jpeg":
                delete_file("section", section.picture)
            for book in section.books:
                book.sectionid = 1
            db.session.commit()
            db.session.delete(section)
            db.session.commit()
            flash("Section deleted successfully.", "success")
        except Exception:
            db.session.rollback()
            flash("An unexpected error occurred while deleting the section.", "error")
    else:
        flash("Section not found.", "error")
    return redirect(url_for("librarian.sections"))


@librarian.route("/librarian/search", methods=["GET", "POST"])
@login_required(role="librarian")
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        return render_template(
            "librarian/search.html",
            title="Search",
            librarian=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("librarian.books"))


@librarian.route("/librarian/sections")
@login_required(role="librarian")
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sections.append(None)
    return render_template(
        "librarian/sections.html",
        title="Sections",
        librarian=current_user,
        navbaractive=["Sections"],
        sections=sections,
    )


@librarian.route("/librarian/section-books/<int:sectionid>")
@login_required(role="librarian")
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (
            sum(feedback.rating for feedback in x.feedbacks),
            x.date_created,
        ),
        reverse=True,
    )
    sorted_books.append(None)
    return render_template(
        "librarian/section_books.html",
        title=f"{section.title} Books",
        librarian=current_user,
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@librarian.route("/librarian/add-book/<int:sectionid>", methods=["GET", "POST"])
@login_required(role="librarian")
def add_book(sectionid):
    form = AddBookForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture = save_picture(form.picture.data, "book\\pictures")
        else:
            picture = "default_book_picture.png"
        if form.pdf_file.data:
            pdf_file = save_pdf(form.pdf_file.data, "book\\pdfs")
        else:
            pdf_file = "sample_pdf.pdf"
        book = Book(
            title=form.title.data,
            author=form.author.data,
            picture=picture,
            description=form.description.data,
            sectionid=sectionid,
            pdf_file=pdf_file,
        )
        db.session.add(book)
        db.session.commit()
        flash(f"New Book {form.title.data} created!", "success")
        return redirect(url_for("librarian.section_books", sectionid=sectionid))
    if request.method == "GET":
        form.sectionid.data = sectionid
    return render_template(
        "librarian/add_book.html",
        title="Add Book",
        form=form,
        librarian=current_user,
        navbaractive=["Books"],
    )


@librarian.route("/librarian/edit-book/<int:bookid>", methods=["GET", "POST"])
@login_required(role="librarian")
def edit_book(bookid):
    book = Book.query.get(bookid)
    form = EditBookForm(current_book=book)
    if form.validate_on_submit():
        if (
            form.picture.data
            or form.pdf_file.data
            or form.delete_picture.data == "yes"
            or book.title != form.title.data
            or book.author != form.author.data
            or book.description != form.description.data
            or book.sectionid != book.sectionid.data
        ):
            book.date_created = datetime.now(timezone.utc).date()
            db.session.commit()
            flash("Book has been updated!", "success")
        if form.picture.data:
            if book.picture != "default_book_picture.png":
                delete_file("book\\pictures", book.picture)
            book.picture = save_picture(form.picture.data, "book\\pictures")
        elif form.delete_picture.data == "yes":
            if book.picture != "default_book_picture.png":
                delete_file("book\\pictures", book.picture)
            book.picture = "default_book_picture.png"
        if form.pdf_file.data:
            if book.pdf_file != "sample_pdf.pdf":
                delete_file("book\\pdfs", book.pdf_file)
            book.pdf_file = save_pdf(form.pdf_file.data, "book\\pdfs")

library_app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user
from library_app import db, bcrypt
from library_app.models import User, Section, Book
from library_app.utils import check_user
from library_app.forms import ResetPasswordForm
from library_app.main.forms import ResetRequestForm
from library_app.utils import send_reset_email

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
@main.route("/sections")
@check_user()
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    return render_template(
        "main/sections.html",
        title="Sections",
        navbaractive=["Sections"],
        sections=sections,
    )


@main.route("/main/search", methods=["GET", "POST"])
@check_user()
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        return render_template(
            "main/search.html",
            title="Search",
            user=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("main.books"))


@main.route("/section-books/<int:sectionid>")
@check_user()
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (sum(feedback.rating for feedback in x.feedbacks), x.date_created),
        reverse=True,
    )
    return render_template(
        "main/section_books.html",
        title=f"{section.title} Books",
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@main.route("/books")
@check_user()
def books():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sorted_sections = []
    for section in sections:
        sorted_books = sorted(
            section.books,
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        sorted_sections.append((section, sorted_books))
    return render_template(
        "main/books.html",
        title="Books",
        navbaractive=["Books"],
        sorted_sections=sorted_sections,
    )


@main.route("/book-info/<int:bookid>")
@check_user()
def book_info(bookid):
    book = Book.query.get(bookid)
    if book is None:
        flash("Book not found", "danger")
        return redirect(url_for("user.books"))
    feedbacks = sorted(
        book.feedbacks, key=lambda x: (x.rating, x.date_created), reverse=True
    )
    pdf_file = url_for("static", filename="book/pdfs/" + book.pdf_file)
    return render_template(
        "main/book_info.html",
        title="Books",
        book=book,
        feedbacks=feedbacks,
        pdf_file=pdf_file,
        navbaractive=["Books"],
        sections=sections,
    )


@main.route("/reset-request", methods=["GET", "POST"])
@check_user()
def reset_request():
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user, 'main.reset_password')
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_request.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )


@main.route("/reset-password/<token>", methods=["GET", "POST"])
@check_user()
def reset_password(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token.", "warning")
        return redirect(url_for("main.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.new_password.data).decode(
            "utf-8"
        )
        db.session.commit()
        flash("Your password has been updated!", "success")
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_password.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )

library_app/templates/librarian/book_info.html
{% extends "librarian/layout.html" %} {% block content %}
<div class="container content-section px-5 pt-4 pb-4">
    <div class="row">
        <div class="mr-4 mb-3">
            <img
                src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                alt="{{ book.title }}"
                class="img-fluid special-card"
                style="height: 25vh"
            />
        </div>
        <div class="">
            <h2>{{ book.title }}</h2>
            <h5>{{ book.author }}</h5>
            <h6>{{ book.section.title }}</h6>
            <p>{{ book.description }}</p>
            <div class="ml-2">
                <a href="{{url_for("librarian.view_book", bookid=book.bookid)}}" class="btn btn-success"><i class="bi bi-eye mr-1"></i>View</a>    
            </div>
            <div class="mt-2 mb-3">
                <div class="row mx-auto">
                    <div class="ml-2 mr-4">
                        <a href="{{url_for("librarian.delete_book", place=1, bookid=book.bookid)}}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this book? All the books content will be removed.');"><i class="bi bi-trash"></i>Delete</a>
                    </div>
                    <div class="ml-1">
                        <a href="{{url_for("librarian.edit_book", bookid=book.bookid)}}" class="btn btn-primary"><i class="bi bi-pencil-square mr-1"></i>Edit</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <h2 class="text-center">Preview</h2>
    <div class="mt-3" id="pdf-viewer" style="text-align: center;"></div>
    <hr />
    {% if issuedbooks|length>0  %}
        {% if issuedbooks|length>4 %}
            <div class="mt-4">
                <h2>User Issued To</h2>
                <div class="container-fluid mt-3">
                    <div class="row flex-row flex-nowrap">
                        {% for issuedbook in issuedbooks %}
                            <div class="container">
                                <div class="card special-card mx-1" style="width: 16rem">
                                    <img
                                        class="card-img-top mx-auto"
                                        src="{{ url_for('static', filename='user/profile_pictures/' + issuedbook.user.profile_picture) }}"
                                        alt="Card image cap"
                                        style="width: 100%; height: 24vh"
                                    />
                                    <div class="card-body">
                                        <h5 class="card-title">{{ issuedbook.user.name }}</h5>
                                        <h6 class="card-title">Till - {{ issuedbook.to_date.strftime('%d %b %Y') }}</h6>
                                    </div>
                                    <div class="container mb-3 text-center">
                                        <a href="{{url_for("librarian.revoke_access", issueid=issuedbook.issueid)}}" class="btn btn-danger"><i class="bi bi-lock mr-1"></i>Revoke</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="mt-4">
                <h2>Users Issued To</h2>
                <div class="row mt-3">
                    {% for issuedbook in issuedbooks %}
                        <div class="col-md-3">
                            <div class="card special-card mx-1">
                                <img
                                    class="card-img-top mx-auto"
                                    src="{{ url_for('static', filename='user/profile_pictures/' + issuedbook.user.profile_picture) }}"
                                    alt="Card image cap"
                                    style="width: 100%; height: 24vh"
                                />
                                <div class="card-body">
                                    <h5 class="card-title">{{ issuedbook.user.name }}</h5>
                                    <h6 class="card-title">Till - {{ issuedbook.to_date.strftime('%d %b %Y') }}</h6>
                                </div>
                                <div class="container mb-3 text-center">
                                    <a href="{{url_for("librarian.revoke_access", issueid=issuedbook.issueid)}}" class="btn btn-danger"><i class="bi bi-lock mr-1"></i>Revoke</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% else %}
    <h2>User Issued To</h2>
    <h4>There are no Users</h4>
    {% endif %}
    <hr />
    <div class="row mt-3">
    <div class="col-md-12">
        <h2 class="mb-3">Feedbacks</h2>
        {% if feedbacks %}
            <div class="list-group">
                {% for feedback in feedbacks %}
                    <div class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ feedback.user.name }}</h5>
                            <small>{{ feedback.date_created }}</small>
                        </div>
                        <div class="d-flex w-100 justify-content-between">
                            <p class="mb-1">Rating: {{ feedback.rating }}/5</p>
                        </div>
                        <p class="mb-1">{{ feedback.content }}</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No feedback available for this book.</p>
        {% endif %}
    </div>
</div>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.js"></script>
<script>
    const pdfPath = "{{ pdf_file }}";
    const viewerContainer = document.getElementById('pdf-viewer');
    const loadingTask = pdfjsLib.getDocument(pdfPath);
    loadingTask.promise.then(pdf => {
        for (let pageNum = 1; pageNum <= 1; pageNum++) {
            pdf.getPage(pageNum).then(page => {
                const container = document.createElement('div');
                container.className = 'pdf-page';
                container.style.display = 'inline-block';
                container.style.margin = '0 auto';
                container.style.marginBottom = '10px';
                container.style.border = '1px solid #ccc';
                viewerContainer.appendChild(container);

                const canvas = document.createElement('canvas');
                container.appendChild(canvas);

                const context = canvas.getContext('2d');
                const viewport = page.getViewport({ scale: 1 });
                const scale = 600 / viewport.height;
                const scaledViewport = page.getViewport({ scale });

                canvas.height = scaledViewport.height;
                canvas.width = scaledViewport.width;

                const renderContext = {
                    canvasContext: context,
                    viewport: scaledViewport
                };
                page.render(renderContext);
            });
        }
    });
</script>
{% endblock %}

library_app/templates/librarian/section_books.html
{% extends "librarian/layout.html" %} {% block content %}
<div class="content-section container px-4 pb-5">
<div class="container mt-3">
    <div class="row">
        <div class="mr-4 mb-3">
            <img src="{{ url_for('static', filename='section/' + section.picture) }}" alt="{{ section.title }}" class="img-fluid special-card" style="max-height: 200px;">
        </div>
        <div class="">
            <h1 class="mb-3">{{ section.title }}</h1>
            <p>{{ section.description }}</p>
            {% if section.sectionid!=1 %}
            <div class="mt-3">
                <a href="{{url_for("librarian.add_book", sectionid=section.sectionid)}}" class="btn btn-success"><i class="bi bi-plus-square mr-1"></i>Add Book</a>
            </div>
            <div class="mt-2">
                <a href="{{url_for("librarian.delete_section", sectionid=section.sectionid)}}" class="btn btn-danger mr-3" onclick="return confirm('Are you sure you want to delete this section? All the Books in this section will be shifted to Miscellaneous.');"><i class="bi bi-trash"></i>Delete</a> 
                <a href="{{url_for("librarian.edit_section", sectionid=section.sectionid)}}" class="btn btn-primary"><i class="bi bi-pencil-square mr-1"></i>Edit</a>
            </div>
            {% else %}
            <div class="mt-4"> 
                <a href="{{url_for("librarian.add_book", sectionid=section.sectionid)}}" class="btn btn-success"><i class="bi bi-plus-square mr-1"></i>Add Book</a>
            </div>
            {% endif %}
        </div>
    </div>
    <hr />
    {% if sorted_books|length>1 %}
    <h2 class="mb-2">Books</h2>
    {% for book in sorted_books %} {% if
    loop.index0 % 4 == 0 %}
        <div class="row mt-3">
            {% endif %} {% if book %}
            <div class="col-md-3">
                <div class="card h-100 special-card mx-1">
                    <a href="{{ url_for('librarian.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                    <img
                        class="card-img-top mx-auto"
                        src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                        alt="Card image cap"
                        style="width: 100%; height: 25vh"
                    />
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <h6 class="card-title">{{ book.author }}</h6>
                        <p class="card-text text-wrap">{{ book.description }}</p>
                    </div></a>
                    <div class="container text-center">
                        <a href="{{url_for("librarian.view_book", bookid=book.bookid)}}" class="btn btn-success"><i class="bi bi-eye mr-1"></i>View</a>    
                    </div>
                    <div class="container mt-2 mb-3 text-center">
                        <div class="row mx-auto">
                            <div class="ml-2 mr-4">
                                <a href="{{url_for("librarian.delete_book", place=0, bookid=book.bookid)}}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this book? All the books content will be removed.');"><i class="bi bi-trash"></i>Delete</a>
                            </div>
                            <div class="ml-1">
                                <a href="{{url_for("librarian.edit_book", bookid=book.bookid)}}" class="btn btn-primary"><i class="bi bi-pencil-square mr-1"></i>Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-md-3">
                <div
                    class="card special-card p-5"
                    style="width: 100%; height: 100%"
                >
                    <div class="card-body d-inline-flex align-items-center">
                        <a
                            href="{{ url_for('librarian.add_book', sectionid=section.sectionid) }}"
                            class="mx-auto"
                        >
                            <i class="bi bi-plus-circle" style="font-size: 6.5rem;color: #28a745;"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endif %} {% if loop.index % 4 == 0 or loop.last %}
        </div>
    {% endif %} {% endfor %} 
    {% else %}
    <h2 class="mb-2">Books</h2>
    <h4 class="mx-auto mt-2">Add Books To View</h4>
    <div class="row mt-3">
        <div class="col-md-3">
            <div
                class="card special-card p-5"
                style="width: 100%; height: 100%"
            >
                <div class="card-body d-inline-flex align-items-center">
                    <a
                        href="{{ url_for('librarian.add_book', sectionid=section.sectionid) }}"
                        class="mx-auto"
                    >
                        <i class="bi bi-plus-circle" style="font-size: 6.5rem;color: #28a745;"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
</div>
{% endblock content %}

library_app/templates/librarian/sections.html
{% extends "librarian/layout.html" %} {% block content %}
<div class="content-section container px-4 pb-4">
{% for section in sections %} {% if loop.index0 % 3 == 0 %}
<div class="container mt-4">
    <div class="row">
        {% endif %} {% if section %}
        <div class="col-md-4">
            <div class="card h-100 special-card mr-1">
                <a href="{{url_for("librarian.section_books", sectionid=section.sectionid)}}">
                <img
                    class="card-img-top mx-auto"
                    src="{{url_for('static', filename='section/' + section.picture)}}"
                    alt="Card image cap"
                    style="width: 100%;height: 30vh;border-bottom: 1px solid #ccc;"/></a>
                <div class="card-body">
                    <a href="{{url_for("librarian.section_books", sectionid=section.sectionid)}}" class="text-decoration-none"><h5 class="card-title">{{section.title}}</h5></a>
                    <a href="{{ url_for('librarian.section_books', sectionid=section.sectionid) }}" class="text-decoration-none text-muted">
                        <p class="card-text text-wrap">{{ section.description }}</p>
                    </a>
                    {% if section.sectionid!=1 %}
                    <div class="container text-center mt-3 ml-2">
                        <a href="{{url_for("librarian.add_book", sectionid=section.sectionid)}}" class="btn btn-success"><i class="bi bi-plus-square mr-1"></i>Add Book</a>
                    </div>
                    <div class="container mt-2"> 
                        <div class="row">
                            <div class="col-md-7 text-left">
                                <a href="{{url_for("librarian.delete_section", sectionid=section.sectionid)}}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this section? All the Books in this section will be shifted to Miscellaneous.');"><i class="bi bi-trash"></i>Delete</a>
                            </div>
                            <div class="col-md-5 text-right">
                                
                                <a href="{{url_for("librarian.edit_section", sectionid=section.sectionid)}}" class="btn btn-primary"><i class="bi bi-pencil-square mr-1"></i>Edit</a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="container mt-5 text-center"> 
                        <a href="{{url_for("librarian.add_book", sectionid=section.sectionid)}}" class="btn btn-success"><i class="bi bi-plus-square mr-1"></i>Add Book</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-md-4">
            <div
                class="card special-card p-5"
                style="width: 100%; height: 100%"
            >
                <div class="card-body d-inline-flex align-items-center">
                    <a href="{{url_for("librarian.add_section")}}" class="mx-auto">
                        <i class="bi bi-plus-circle" style="font-size: 6.5rem;color: #28a745;"></i>
                    </a>
                </div>
            </div>
        </div>
        {% endif %} {% if loop.index % 3 == 0 or loop.last %}
    </div>
</div>
{% endif %} {% endfor %}
</div>
{% endblock content %}