library_app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user
from library_app import db, bcrypt
from library_app.models import User, Section, Book
from library_app.utils import check_user
from library_app.forms import ResetPasswordForm
from library_app.main.forms import ResetRequestForm
from library_app.utils import send_reset_email

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
@main.route("/sections")
@check_user()
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    return render_template(
        "main/sections.html",
        title="Sections",
        navbaractive=["Sections"],
        sections=sections,
    )


@main.route("/main/search", methods=["GET", "POST"])
@check_user()
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        return render_template(
            "main/search.html",
            title="Search",
            user=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("main.books"))


@main.route("/section-books/<int:sectionid>")
@check_user()
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (sum(feedback.rating for feedback in x.feedbacks), x.date_created),
        reverse=True,
    )
    return render_template(
        "main/section_books.html",
        title=f"{section.title} Books",
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@main.route("/books")
@check_user()
def books():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sorted_sections = []
    for section in sections:
        sorted_books = sorted(
            section.books,
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        sorted_sections.append((section, sorted_books))
    return render_template(
        "main/books.html",
        title="Books",
        navbaractive=["Books"],
        sorted_sections=sorted_sections,
    )


@main.route("/book-info/<int:bookid>")
@check_user()
def book_info(bookid):
    book = Book.query.get(bookid)
    if book is None:
        flash("Book not found", "danger")
        return redirect(url_for("user.books"))
    feedbacks = sorted(
        book.feedbacks, key=lambda x: (x.rating, x.date_created), reverse=True
    )
    pdf_file = url_for("static", filename="book/pdfs/" + book.pdf_file)
    return render_template(
        "main/book_info.html",
        title="Books",
        book=book,
        feedbacks=feedbacks,
        pdf_file=pdf_file,
        navbaractive=["Books"],
        sections=sections,
    )


@main.route("/reset-request", methods=["GET", "POST"])
@check_user()
def reset_request():
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user, 'main.reset_password')
        flash(
            "An email has been sent with instructions to reset your password.", "info"
        )
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_request.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )


@main.route("/reset-password/<token>", methods=["GET", "POST"])
@check_user()
def reset_password(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token.", "warning")
        return redirect(url_for("main.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = bcrypt.generate_password_hash(form.new_password.data).decode(
            "utf-8"
        )
        db.session.commit()
        flash("Your password has been updated!", "success")
        if user.get_urole() == "user":
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("librarian.login"))
    return render_template(
        "main/reset_password.html",
        user=current_user,
        navbaractive=["Login"],
        title="Reset Password",
        form=form,
    )

library_app/user/routes.py
import secrets
from datetime import datetime, timezone
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    request,
)
from flask_login import login_user, current_user, logout_user
from library_app import db, bcrypt
from library_app.models import User, Section, Request, Feedback, IssuedBook, Book
from library_app.forms import (
    LoginForm,
    EditProfileForm,
    ChangePasswordForm,
    ResetPasswordForm,
    DeleteAccountForm,
)
from library_app.user.forms import (
    RegistrationForm,
    BookRequestForm,
    FeedbackForm,
    EditFeedbackForm,
)
from library_app.utils import (
    login_required,
    check_user,
    save_picture,
    send_reset_email,
    delete_file,
)
from library_app.user.utils import generate_plots

user = Blueprint("user", __name__)


@user.route("/user/register", methods=["GET", "POST"])
@check_user()
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if form.profile_picture.data:
            profile_picture = save_picture(form.profile_picture.data, "user\\profile_pictures")
        else:
            profile_picture = "default_profile_picture.png"
        user = User(
            name=form.name.data,
            email=form.email.data,
            username=form.username.data,
            password=form.password.data,
            profile_picture=profile_picture,
        )
        print(form.profile_picture.data, user)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}!", "success")
        return redirect(url_for("user.login"))
    return render_template(
        "user/register.html",
        user=current_user,
        title="Register",
        form=form,
        navbaractive=["Login"],
    )


@user.route("/user/login", methods=["GET", "POST"])
@check_user()
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.urole == "user":
                flash(f"You have logged in successfully!", "success")
                login_user(user, remember=form.remember.data)
                nextpage = request.args.get("next")
                return (
                    redirect(nextpage) if nextpage else redirect(url_for("user.books"))
                )
            elif user.urole == "librarian":
                flash(f"Please log in as librarian", "info")
                return redirect(url_for("librarian.login"))
            else:
                return redirect(url_for("main.error"))
        else:
            flash(f"Invalid username or Password", "danger")
    return render_template(
        "user/login.html", title="Login", form=form, navbaractive=["Login"], width=True
    )


@user.route("/user/sections")
@login_required(role="user")
def sections():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    return render_template(
        "user/sections.html",
        title="Sections",
        navbaractive=["Sections"],
        user=current_user,
        sections=sections,
    )


@user.route("/user/search", methods=["GET", "POST"])
@login_required(role="user")
def search():
    if request.method == "POST":
        search_term = request.form["search_term"]
        sections = (
            Section.query.filter(Section.title.ilike(f"%{search_term}%"))
            .order_by(Section.date_created.desc())
            .all()
        )
        books = Book.query.filter(Book.title.ilike(f"%{search_term}%")).all()
        books.sort(
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        authors = Book.query.filter(Book.author.ilike(f"%{search_term}%")).all()
        authors.sort(
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        return render_template(
            "user/search.html",
            title="Search",
            user=current_user,
            sections=sections,
            books=books,
            authors=authors,
        )
    else:
        return redirect(url_for("user.books"))


@user.route("/user/section-books/<int:sectionid>")
@login_required(role="user")
def section_books(sectionid):
    section = Section.query.get(sectionid)
    sorted_books = sorted(
        section.books,
        key=lambda x: (
            sum(feedback.rating for feedback in x.feedbacks),
            x.date_created,
        ),
        reverse=True,
    )
    return render_template(
        "user/section_books.html",
        title=f"{section.title} Books",
        user=current_user,
        navbaractive=["Books"],
        section=section,
        sorted_books=sorted_books,
    )


@user.route("/user/books")
@login_required(role="user")
def books():
    sections = Section.query.order_by(Section.date_created.desc()).all()
    sections.sort(key=lambda x: len(x.books), reverse=True)
    sorted_sections = []
    for section in sections:
        sorted_books = sorted(
            section.books,
            key=lambda x: (
                sum(feedback.rating for feedback in x.feedbacks),
                x.date_created,
            ),
            reverse=True,
        )
        sorted_sections.append((section, sorted_books))
    issuedbookids = {
        issuedbook.bookid: issuedbook.issueid
        for issuedbook in current_user.issuedbooks
        if issuedbook.status == "current"
    }
    feedbackbookids = {
        feedback.bookid: feedback.feedbackid
        for feedback in current_user.feedbacks
        if feedback.bookid in issuedbookids
    }
    return render_template(
        "user/books.html",
        title="Books",
        user=current_user,
        navbaractive=["Books"],
        issuedbookids=issuedbookids,
        feedbackbookids=feedbackbookids,
        sorted_sections=sorted_sections,
    )


@user.route("/user/book-info/<int:bookid>")
@login_required(role="user")
def book_info(bookid):
    book = Book.query.get(bookid)
    if book is None:
        flash("Book not found", "danger")
        return redirect(url_for("user.books"))
    feedbacks = sorted(
        book.feedbacks, key=lambda x: (x.rating, x.date_created), reverse=True
    )
    pdf_file = url_for("static", filename="book/pdfs/" + book.pdf_file)
    issuedbookids = {
        issuedbook.bookid: issuedbook.issueid
        for issuedbook in current_user.issuedbooks
        if issuedbook.status == "current"
    }
    feedbackbookids = {
        feedback.bookid: feedback.feedbackid
        for feedback in current_user.feedbacks
        if feedback.bookid in issuedbookids
    }
    return render_template(
        "user/book_info.html",
        title="Books",
        user=current_user,
        book=book,
        feedbacks=feedbacks,
        issuedbookids=issuedbookids,
        feedbackbookids=feedbackbookids,
        pdf_file=pdf_file,
        navbaractive=["Books"],
        sections=sections,
    )


@user.route("/user/book-request/<int:bookid>", methods=["GET", "POST"])
@login_required(role="user")
def book_request(bookid):
    cou1 = 0
    for issuedbook in current_user.issuedbooks:
        if issuedbook.bookid == bookid and issuedbook.status=="current":
            flash("The book has already been issued.", "info")
            return redirect(url_for("user.books"))
        if issuedbook.status == "current":
            cou1 += 1
    cou2 = 0
    for user_request in current_user.requests:
        if user_request.bookid == bookid and user_request.status == "pending":
            flash("The request has already been placed.", "info")
            return redirect(url_for("user.books"))
        if user_request.status == "pending":
            cou2 += 1
    if cou1 + cou2 >= 5:
        flash("You can only borrow 5 books at maximum.", "danger")
        return redirect(url_for("user.mybooks"))
    form = BookRequestForm()
    if form.validate_on_submit():
        book_request = Request(
            userid=current_user.userid,
            days=form.days.data,
            bookid=form.bookid.data,
        )
        db.session.add(book_request)
        db.session.commit()
        flash(f"The book has been requested!", "success")
        return redirect(url_for("user.mybooks"))
    if request.method == "GET":
        form.bookid.data = bookid
        form.days.data = 3
    return render_template(
        "user/book_request.html",
        title="Book Request",
        form=form,
        user=current_user,
        navbaractive=["Books"],
    )


@user.route("/user/delete-request/<int:requestid>")
@login_required(role="user")
def delete_request(requestid):
    book_request = Request.query.get(requestid)
    if book_request:
        if current_user.userid == book_request.userid:
            flash("The request has been deleted.", "success")
            db.session.delete(book_request)
            db.session.commit()
        else:
            abort(403)
    else:
        flash("The book doesn't exist", "danger")
    return redirect(url_for("user.mybooks"))


@user.route("/user/mybooks")
@login_required(role="user")
def mybooks():
    current, completed = [], []
    for issuedbook in IssuedBook.query.filter_by(userid=current_user.userid).all():
        if issuedbook.status == "current":
            if datetime.now(timezone.utc).date() > issuedbook.to_date:
                issuedbook.status = "returned"
                db.session.commit()
        if issuedbook.status == "current":
            current.append(issuedbook)
        else:
            completed.append(issuedbook)
    current.sort(
        key=lambda x: (
            x.to_date,

library_app/templates/user/change_password.html
{% extends "user/layout.html" %} {% block content %}
<div class="content-section mx-auto w-50">
    <form
        method="POST"
        action=""
        class="form mx-auto w-75 mb-3 mt-3"
        enctype="multipart/form-data"
    >
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 h2 font-weight-normal">
                Change Password
            </legend>
            <div class="form-group">
                {{ form.old_password.label(class='h5 font-weight-normal
                form-control-label mt-2') }} {% if form.old_password.errors %}
                {{ form.old_password(class="form-control password form-control-lg
                is-invalid mt-1") }}
                <div>
                    {% for error in form.old_password.errors %}
                    <p class="text-danger mt-1">*{{error}}</p>
                    {% endfor %}
                </div>

                {% else %} {{ form.old_password(class="form-control password
                form-control-lg mt-1") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.new_password.label(class='h5 font-weight-normal
                form-control-label mt-2') }} {% if form.new_password.errors %}
                {{ form.new_password(class="form-control password form-control-lg
                is-invalid mt-1") }}
                <div>
                    {% for error in form.new_password.errors %}
                    <p class="text-danger mt-1">*{{error}}</p>
                    {% endfor %}
                </div>

                {% else %} {{ form.new_password(class="form-control password
                form-control-lg mt-1") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class='h5 font-weight-normal
                form-control-label mt-2') }} {% if not form.new_password.errors
                and form.confirm_password.errors %} {{
                form.confirm_password(class="form-control password form-control-lg
                is-invalid mt-1") }}
                <div>
                    {% for error in form.confirm_password.errors %}
                    <p class="text-danger mt-1">*{{error}}</p>
                    {% endfor %}
                </div>

                {% else %} {{ form.confirm_password(class="form-control password
                form-control-lg mt-1") }} {% endif %}
            </div>
            <div>
                <input type="checkbox" id="showPass" onchange="showPassword()">
                <label for="showPass">Show</label>
            </div>
            <p class="text-muted mt-2" style="font-size: 1.15rem;"><a href="{{url_for('user.reset_request', token=2)}}">Forgot Password?</a></p>
        </fieldset>
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-lg btn-danger" href="{{url_for("user.account")}}"><i class="bi bi-x-circle mr-1"></i>Cancel</a>
            </div>
            <div class="col-md-6 text-right">
                <button class="btn btn-lg btn-success" id="submit" name="submit" type="submit" value="Change"><i class="bi bi-arrow-clockwise mr-1"></i>Change</button>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

library_app/templates/user/search.html
{% extends "user/layout.html" %}
{% block content %}
<div class="content-section container px-4 pb-5">
    {% if sections|length>0 or books|length>0 or authors|length>0 %}
        {% if sections|length > 0 %}
            {% if sections|length > 3 %}
                <div class="container mt-4">
                    <h2>Section Matches</h2>
                    <div class="container-fluid mt-3" style="overflow-x: auto;">
                        <div class="row flex-row flex-nowrap">
                            {% for section in sections %}
                                <div class="container">
                                    <div class="card special-card mx-1" style="width: 22rem;">
                                        <a href="{{ url_for("user.section_books", sectionid=section.sectionid) }}">
                                            <img class="card-img-top mx-auto"
                                                src="{{ url_for('static', filename='section/' + section.picture) }}"
                                                alt="Card image cap"
                                                style="width: 100%; height: 30vh;"
                                            />
                                        </a>
                                        <div class="card-body">
                                            <a href="{{ url_for("user.section_books", sectionid=section.sectionid) }}"
                                                class="text-decoration-none">
                                                <h5 class="card-title">{{ section.title }}</h5>
                                            </a>
                                            <a href="{{ url_for('user.section_books', sectionid=section.sectionid) }}"
                                                class="text-decoration-none text-muted">
                                                <p class="card-text text-wrap">{{ section.description }}</p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="container mt-4">
                    <h2>Section Matches</h2>
                    <div class="row mt-3">
                        {% for section in sections %}
                            <div class="col-md-4">
                                <div class="card special-card mx-1">
                                    <a href="{{ url_for("user.section_books", sectionid=section.sectionid) }}">
                                        <img class="card-img-top mx-auto"
                                            src="{{ url_for('static', filename='section/' + section.picture) }}"
                                            alt="Card image cap"
                                            style="width: 100%; height: 30vh;"
                                        />
                                    </a>
                                    <div class="card-body">
                                        <a href="{{ url_for("user.section_books", sectionid=section.sectionid) }}"
                                            class="text-decoration-none">
                                            <h5 class="card-title">{{ section.title }}</h5>
                                        </a>
                                        <a href="{{ url_for('user.section_books', sectionid=section.sectionid) }}"
                                            class="text-decoration-none text-muted">
                                            <p class="card-text text-wrap">{{ section.description }}</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
        {% if books|length>0  %}
            {% if books|length>4 %}
                <div class="container mt-4">
                    <h2>Book Matches</h2>
                    <div class="container-fluid mt-3">
                        <div class="row flex-row flex-nowrap">
                            {% for book in books %}
                                <div class="container">
                                    <div class="card special-card mx-1" style="width: 16rem">
                                        <a href="{{ url_for('user.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                                        <img
                                            class="card-img-top mx-auto"
                                            src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                                            alt="Card image cap"
                                            style="width: 100%; height: 24vh"
                                        />
                                        <div class="card-body">
                                            <h5 class="card-title">{{ book.title }}</h5>
                                            <h6 class="card-title">{{ book.author }}</h6>
                                            <p class="card-text text-wrap">{{ book.description }}</p>
                                        </div></a>
                                        <div class="container mt-1 mb-3 text-center">
                                            <a
                                                href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                                                class="btn btn-success"
                                                ><i class="bi bi-send mr-1"></i>Request</a
                                            >
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="container mt-4">
                    <h2>Book Matches</h2>
                    <div class="row mt-3">
                        {% for book in books %}
                            <div class="col-md-3">
                                <div class="card special-card mx-1">
                                    <a href="{{ url_for('user.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                                    <img
                                        class="card-img-top mx-auto"
                                        src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                                        alt="Card image cap"
                                        style="width: 100%; height: 24vh"
                                    />
                                    <div class="card-body">
                                        <h5 class="card-title">{{ book.title }}</h5>
                                        <h6 class="card-title">{{ book.author }}</h6>
                                        <p class="card-text text-wrap">{{ book.description }}</p>
                                    </div></a>
                                    <div class="container mt-1 mb-3 text-center">
                                        <a
                                            href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                                            class="btn btn-success"
                                            ><i class="bi bi-send mr-1"></i>Request</a
                                        >
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
        {% if authors|length>0  %}
            {% if authors|length>4 %}
                <div class="container mt-4">
                    <h2>Author Matches</h2>
                    <div class="container-fluid mt-3">
                        <div class="row flex-row flex-nowrap">
                            {% for book in authors %}
                                <div class="container">
                                    <div class="card special-card mx-1" style="width: 16rem">
                                        <a href="{{ url_for('user.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                                        <img
                                            class="card-img-top mx-auto"
                                            src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                                            alt="Card image cap"
                                            style="width: 100%; height: 24vh"
                                        />
                                        <div class="card-body">
                                            <h5 class="card-title">{{ book.title }}</h5>
                                            <h6 class="card-title">{{ book.author }}</h6>
                                            <p class="card-text text-wrap">{{ book.description }}</p>
                                        </div></a>
                                        <div class="container mt-1 mb-3 text-center">
                                            <a
                                                href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                                                class="btn btn-success"
                                                ><i class="bi bi-send mr-1"></i>Request</a
                                            >
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="container mt-4">
                    <h2>Author Matches</h2>
                    <div class="row mt-3">
                        {% for book in authors %}
                            <div class="col-md-3">
                                <div class="card special-card mx-1">
                                    <a href="{{ url_for('user.book_info', bookid=book.bookid) }}" class="text-decoration-none text-muted">
                                    <img
                                        class="card-img-top mx-auto"
                                        src="{{ url_for('static', filename='book/pictures/' + book.picture) }}"
                                        alt="Card image cap"
                                        style="width: 100%; height: 24vh"
                                    />
                                    <div class="card-body">
                                        <h5 class="card-title">{{ book.title }}</h5>
                                        <h6 class="card-title">{{ book.author }}</h6>
                                        <p class="card-text text-wrap">{{ book.description }}</p>
                                    </div></a>
                                    <div class="container mt-1 mb-3 text-center">
                                        <a
                                            href="{{ url_for('user.book_request', bookid=book.bookid) }}"
                                            class="btn btn-success"
                                            ><i class="bi bi-send mr-1"></i>Request</a
                                        >
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% else %}
        <div class="container mt-4">
            <h2 class="mx-auto mt-3">No Results Found.</h2>
        </div>
    {% endif %}
</div>
{% endblock content %}

library_app/templates/user/stats.html
{% extends "user/layout.html" %} 
{% block content %}
<div class="content-section container">
    <div class="row justify-content-center mt-4 mb-5">
        <div class="col-md-6 text-center">
            <h2 class="text-center mb-4">Books Read</h2>
            <img src="{{ url_for('static', filename='user/stats/' + user.username + '_bar_chart.png') }}" class="img-fluid ml-4 mt-4" style="height: 50vh;">
        </div>
        <div class="col-md-6 text-center">
            <h2 class="text-center mb-4">Section Distribution</h2>
            <img src="{{ url_for('static', filename='user/stats/' + user.username + '_pie_chart.png') }}" class="img-fluid" style="height: 50vh;width:28w">
        </div>
    </div>
</div>
{% endblock content %}